config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'users/show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  enum role: { 'member': 0, "admin": 1 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github]

  validates :username, presence: true, uniqueness: { case_sensitive: true }
  validate :validate_username

  attr_writer :login

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value',
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  def self.from_omniauth(auth)
    username = auth.info.name.gsub(/\s+/, '').downcase

    where(email: auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.username = username
      user.full_name = auth.info.name
      user.avatar_url = auth.info.image

      user.password = Devise.friendly_token[0, 20]
    end
  end

  private

  def validate_username
    return unless User.where(email: username).exists?

    errors.add(:username, :invalid)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery except: :create

  def after_sign_in_path_for(_resource)
    root_path
  end

  def log_in_user
    return if user_signed_in?

    redirect_to new_user_session_path, status: :see_other
  end

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: %i[login password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_auth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # profile page
  def show; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_img(user)
    if user.avatar_url.present?
      url_for(user.avatar_url)
    else
      gravatar_url(user)
    end
  end

  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id  = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=retro"
    image_tag(gravatar_url, alt: user.username, class: 'gravatar')
  end

  def gravatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=250&d=retro"
  end
end

app/views/home/index.html.erb
<section class="text-center">
  <div class='w-full min-h-[100svh] sm:min-h-0 pt-16 -mb-20 sm:mb-20'>
    <h1>RevVocal</h1>
    <h2>Engine Harmonics Challenge</h2>

    <%= image_tag "hero.png", class: "py-10 sm:p-20 sm:max-w-[500px] sm:mx-auto animate-" %>

    <div class="flex gap-4 justify-center">
      <button class="bg-emerald-500 hover:bg-emerald-400 dark:bg-emerald-600 dark:hover:bg-emerald-500 text-white px-3 py-2 rounded-md duration-500 hover:cursor-pointer">Start a Game</button>

      <button class="bg-blue-500 hover:bg-blue-400 dark:bg-blue-600 dark:hover:bg-blue-500 text-white px-3 py-2 rounded-md duration-500 hover:cursor-pointer">Upload a Sound</button>
    </div>
  </div>

  <p class="max-w-2xl mx-auto text-xl mb-10">Dive into the world of motorcycles with authentic engine sounds from various models and brands.</p>

  <p class="max-w-2xl mx-auto text-xl mb-10">Sharpen your auditory senses as you listen to and identify different motorcycle engines, testing your knowledge and passion.</p>

  <p class="max-w-2xl mx-auto text-xl mb-10">Compete against fellow enthusiasts by correctly identifying as many engine sounds as possible within the time limit, aiming for the top spot on the global leaderboard.</p>
</section>

app/views/layouts/_flash.html.erb
<div class="flashes">
  <% flash.each do |type, message| %>
    <%= content_tag(:div, message, class: "flash #{type}", data: { controller: "flash" }) %>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav data-controller='nav' data-nav-target='nav' class="pt-2 px-4 md:flex md:flex-col fixed md:h-[100svh] md:w-fit w-full z-50 transition-colors">
  <div class="flex justify-between items-center">
    <%# logo %>
    <span>
      <%= image_tag "logo_nav.svg", class: 'h-10 w-auto md:mx-7 my-3' %>
    </span>

    <%# nav button %>
    <button type='button' data-action="nav#toggleNav" class="text-3xl cursor-pointer md:hidden block">
      <ion-icon data-nav-target="menu" class="p-2 rounded-full shadow-md dark:shadow-gray-800" name="menu"></ion-icon>
    </button>
  </div>

  <ul data-nav-target='list' class="md:flex flex-col md:ml-4 md:static absolute w-full h-[100svh] left-0 md:w-auto md:py-0 py-4 md:pl-0 pl-0 transition-transform md:translate-x-0 translate-x-full bg-lm-1 dark:bg-dm-1 md:bg-transparent dark:md:bg-transparent">
    <%= link_to root_path do %>
      <li class="mr-4 md:mx-1 my-3 text-xl hover:bg-gray-200 dark:hover:bg-gray-800 md:w-fit py-2 px-3 rounded-3xl duration-500 flex justify-end md:justify-normal md:flex-row-reverse items-center gap-3">
        <p>Home</p>
        <ion-icon name="home" class="text-2xl"></ion-icon>
      </li>
    <% end %>

    <% if current_user %>
      <%= link_to users_show_path do %>
        <li class="mr-4 md:mx-1 my-3 text-xl hover:bg-gray-200 dark:hover:bg-gray-800 md:w-fit py-2 px-3 rounded-3xl duration-500 flex justify-end md:justify-normal md:flex-row-reverse items-center gap-3">
          <p>Profile</p>
          <ion-icon name="person-circle" class="text-2xl"></ion-icon>
        </li>
      <% end %>

      <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
        <li class="mr-4 md:mx-1 my-3 text-xl hover:bg-gray-200 dark:hover:bg-gray-800 md:w-fit py-2 px-3 rounded-3xl duration-500 flex justify-end md:justify-normal md:flex-row-reverse items-center gap-3">
          <p>Log out</p>
          <ion-icon name="log-out" class="text-2xl"></ion-icon>
        </li>
      <% end %>
    <% else %>
      <%= link_to new_session_path(:user) do %>
        <li class="mr-4 md:mx-1 my-3 text-xl hover:bg-gray-200 dark:hover:bg-gray-800 md:w-fit py-2 px-3 rounded-3xl duration-500 flex justify-end md:justify-normal md:flex-row-reverse items-center gap-3">
          <p>Log in</p>
          <ion-icon name="log-in" class="text-2xl"></ion-icon>
        </li>
      <% end %>
    <% end %>

    <%# dark mode button %>
    <li class="mr-6 md:mx-1 my-3 flex justify-end md:justify-normal">
      <button type='button' data-action='nav#toggleMode' class="text-2xl px-2 pt-2 cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-800 rounded-full duration-500">
        <ion-icon data-nav-target='mode' name="sunny-outline"></ion-icon>
      </button>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RevVocal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path("logo_nav.svg") %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# tailwind %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <meta name="color-scheme" content="light dark">

    <%# ion icons %>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </head>
  <body class='poppins bg-lm-1 text-dm-1 dark:bg-dm-1 dark:text-lm-1 h-[100svh] lm-svg dark:dm-svg' >
    <%= render "layouts/flash" %>

    <header>
      <%= render 'layouts/nav' %>
    </header>

    <main class="max-w-7xl mx-auto flex py-20 px-4 md:pl-52 md:py-4">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/show.html.erb
<section class="w-full py-10 md:py-20">
  <div class="h-[45px] md:h-[100px] rounded-t-[6px] bg-primary"></div>
  <div class="flex flex-col items-start md:items-center py-4 bg-white dark:bg-dm-2 mb-3 rounded-b-[6px]">

    <%= image_tag profile_img(current_user), class: "border-solid border-4 md:border-8 border-primary rounded-full w-20 h-20 md:w-40 md:h-40 absolute left-12 md:left-auto top-[8.5rem] md:top-28" %>

    <%# edit user button %>
    <div class="flex justify-end w-full pr-4">
      <%= link_to "Edit profile", edit_user_registration_path(current_user), class: "bg-gray-600 hover:bg-gray-500 dark:bg-gray-700 dark:hover:bg-gray-600 text-white px-3 py-2 rounded-lg duration-500" %>
    </div>

    <div class='flex flex-col items-center md:items-start md:gap-x-9 md:mt-9 p-8 md:pt-0'>
      <div>
        <% unless current_user.full_name.present? %>
          <h1 class='text-3xl text-left md:text-center font-bold'><%= current_user.username %></h1>
        <% else %>
          <h1 class='text-3xl text-left md:text-center font-bold'><%= current_user.full_name%></h1>
          <h3 class='text-2xl text-left md:text-center text-gray-600 dark:text-gray-400 font-bold'><%= current_user.username%></h1>
        <% end %>
      </div>
    </div>
  </div>
</div>